# Generated by Django 3.2.4 on 2021-07-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('v_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_address', models.CharField(max_length=20)),
                ('v_growth', models.CharField(max_length=20)),
                ('v_employ', models.CharField(max_length=20)),
                ('v_sep', models.CharField(max_length=20)),
                ('v_predict', models.BigIntegerField()),
                ('v_doctor', models.BigIntegerField()),
                ('v_master', models.BigIntegerField()),
                ('v_bachelor', models.BigIntegerField()),
                ('v_college', models.BigIntegerField()),
                ('v_high', models.BigIntegerField()),
                ('v_region', models.CharField(max_length=50)),
                ('v_field', models.CharField(max_length=50)),
            ],
        ),
    ]
